from sqlalchemy import Sequence

client_id_seq = Sequence('S_CLIENT')
cardgroup_id_seq = Sequence('S_CARDGROUP')
virtual_group_id_seq = Sequence("S_VIRTGROUP")
company_id_seq = Sequence("S_COMPANY")
company2role_id_seq = Sequence("S_COMPANY2ROLE")
currency_id_seq = Sequence("S_CURRENCY")
accounting_file_id_seq = Sequence("S_ACCOUNTINGFILE")
simcard_id_seq = Sequence("S_CARD")
simcard_imsi_id_seq = Sequence("S_SIMCARDIMSI")
simcard_number_id_seq = Sequence("S_SIMNUMBER")
simcard_number_rate_id_seq = Sequence("S_SIMNUMBERRATE")
basecard_id_seq = Sequence("S_CARD")
account_id_seq = Sequence("S_ACCOUNT")
card_series_id_seq = Sequence("S_CARDSERIES")
